version: "3.3"
services:
    mqtt:
       image: eclipse-mosquitto:latest
       ports: 
           - "1883:1883"
           - "9001:9001"
    runmo_subscription:
        build: 
            context: ./
            dockerfile: Dockerfile
        environment:
            s3_bucket: runmo_bucket
            s3_ket: runmo
